language: node_js
node_js:
  - "6.9.4"
#services:
#  - mongodb

notifications:
  email: false
  
before_script:
  - npm install bower
  - npm install grunt
  - npm install grunt-bower-task
  - npm install grunt-cli
#  - mongo mydb_test --eval 'db.addUser("travis", "test");'